plugins {
    id 'java'
    id 'checkstyle'
    id 'com.diffplug.spotless' version '7.2.1'
}

group = 'com.fishercoder'
version = '1.0-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.javadoc {
    options.encoding = 'UTF-8'
}

tasks.compileJava {
    options.encoding = 'UTF-8'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation 'org.apache.commons:commons-collections4:4.0'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:6.1.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.3'

    testImplementation 'org.assertj:assertj-core:3.27.7'
    compileOnly 'org.projectlombok:lombok:1.18.48'
    annotationProcessor 'org.projectlombok:lombok:1.18.48'
    testCompileOnly 'org.projectlombok:lombok:1.18.48'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.48'
}

testing {
    suites {
        test {
            useJUnitJupiter()
        }
    }
}

tasks.withType(Test).configureEach {
    maxParallelForks = Runtime.runtime.availableProcessors()
}

checkstyle {
    toolVersion = '6.17'
    config = rootProject.resources.text.fromFile('fishercoder_checkstyle.xml')
}

spotless {
    java {
        encoding 'UTF-8'
        target fileTree(projectDir) {
            include '**/src/**/*.java'
            exclude '**/build/**'
        }
        importOrder '\\#', '', '*'
        removeUnusedImports()
        googleJavaFormat('1.30.0').aosp()
        toggleOffOn()
        endWithNewline()
    }
}
