package com.fishercoder;

import com.fishercoder.solutions._737;
import org.junit.BeforeClass;
import org.junit.Test;

import static org.junit.Assert.assertEquals;

public class _737Test {
    private static _737.Solution1 solution1;
    private static String[] words1;
    private static String[] words2;
    private static String[][] pairs;

    @BeforeClass
    public static void setup() {
        solution1 = new _737.Solution1();
    }

    @Test
    public void test1() {
        words1 = new String[]{"great", "acting", "skills"};
        words2 = new String[]{"fine", "drama", "talent"};
        pairs = new String[][]{
                {"great", "fine"},
                {"acting", "drama"},
                {"skills", "talent"}
        };
        assertEquals(true, solution1.areSentencesSimilarTwo(words1, words2, pairs));
    }

    @Test
    public void test2() {
        words1 = new String[]{"great", "acting", "skills"};
        words2 = new String[]{"fine", "drama", "talent"};
        pairs = new String[][]{
                {"great", "good"},
                {"fine", "good"},
                {"drama", "acting"},
                {"skills", "talent"}
        };
        assertEquals(true, solution1.areSentencesSimilarTwo(words1, words2, pairs));
    }


    @Test
    public void test3() {
        String[] words1 = new String[]{"one", "excellent", "meal"};
        String[] words2 = new String[]{"one", "good", "dinner"};
        String[][] pairs = new String[][]{
                {"great", "good"},
                {"extraordinary", "good"},
                {"well", "good"},
                {"wonderful", "good"},
                {"excellent", "good"},
                {"dinner", "meal"},
                {"fine", "good"},
                {"nice", "good"},
                {"any", "one"},
                {"unique", "one"},
                {"some", "one"},
                {"the", "one"},
                {"an", "one"},
                {"single", "one"},
                {"a", "one"},
                {"keep", "own"},
                {"truck", "car"},
                {"super", "very"},
                {"really", "very"},
                {"actually", "very"},
                {"extremely", "very"},
                {"have", "own"},
                {"possess", "own"},
                {"lunch", "meal"},
                {"super", "meal"},
                {"food", "meal"},
                {"breakfast", "meal"},
                {"brunch", "meal"},
                {"wagon", "car"},
                {"automobile", "car"},
                {"auto", "car"},
                {"fruits", "meal"},
                {"vehicle", "car"},
                {"entertain", "have"},
                {"drink", "have"},
                {"eat", "have"},
                {"take", "have"},
        };
        assertEquals(true, solution1.areSentencesSimilarTwo(words1, words2, pairs));
    }

    @Test
    public void test4() {
        words1 = new String[]{"jrocadcojmybpxmuj", "livgsrfvgtovcurzq", "mnrdscqkycodx", "wgcjlntupylayse", "tglnshmqlmkqqfbpf", "uzlxmaoro", "narvuaqmmkqhd", "xozoyaqxtbustrymo", "jrocadcojmybpxmuj", "ainlwrwabqcwq", "qnjidlmwmxxjgntez", "bbchthovla", "vaufbmwdrupcxpg", "zwwgloilddclufwze", "tyxrlpmcy", "wtjtdrlm", "edurtetzseifez", "yzxogkunvohdmro", "livgsrfvgtovcurzq", "wmpvjvzljhnaxvp", "rqbswlkw", "umlzibkkpsyvpdol", "jkcmceinlyhi", "wlvmfxbleuot", "aeloeauxmc", "ooyllkxg", "wlvmfxbleuot", "cuewcvuy", "vaufbmwdrupcxpg", "bbchthovla", "arigdtezmyz", "yzxogkunvohdmro", "wrszraxxdum", "dhmiuqhqlsprxy", "xpmxtfyvjrnujyxjh", "bfxbncez", "cjjkmybleu", "mnrdscqkycodx", "mzfpofjn", "livgsrfvgtovcurzq", "shfzcyboj", "xozoyaqxtbustrymo", "xozoyaqxtbustrymo", "orlzzpytpzazxr", "filnwifbukdqijgr", "fllqjtnxwmfoou", "mkmawbogphdttd", "rthpxoxyyiy", "dkhfozltuckwog", "wmpvjvzljhnaxvp", "dhmiuqhqlsprxy", "yltljjairlkrmdq", "cuewcvuy", "subzoyxjkfiwmfb", "mzvbgcizeeth", "narvuaqmmkqhd", "tglnshmqlmkqqfbpf", "rpesfkhfjucj", "xrgfejybbkezgor", "vaufbmwdrupcxpg", "czlgbqzffodsoxng", "suvvqdiceuogcmv", "fllqjtnxwmfoou", "yltljjairlkrmdq", "bubwouozgs", "mnrdscqkycodx", "rqbswlkw", "ooyllkxg", "livgsrfvgtovcurzq", "rthpxoxyyiy", "pyzcbpjhntpefbq", "wtjtdrlm", "rztcppnmud", "inuzvkgolupxelcal", "pdxsxjop", "wmpvjvzljhnaxvp", "xydwvemqvtgvzl", "hqpnoczciajvkbdy", "rvihrzzkt", "jzquemjzpvfbka", "gkqrglav", "qyaxqaqxiwr", "mzvbgcizeeth", "umlzibkkpsyvpdol", "vaufbmwdrupcxpg", "ooyllkxg", "arigdtezmyz", "bubwouozgs", "wtjtdrlm", "xozoyaqxtbustrymo", "jrocadcojmybpxmuj", "rnlryins", "fllqjtnxwmfoou", "livgsrfvgtovcurzq", "czlgbqzffodsoxng", "hlcsiukaroscfg", "bfxbncez", "ainlwrwabqcwq", "vaufbmwdrupcxpg", "vaufbmwdrupcxpg"};
        words2 = new String[]{"jrocadcojmybpxmuj", "livgsrfvgtovcurzq", "mnrdscqkycodx", "wgcjlntupylayse", "bbchthovla", "bfxbncez", "ztisufueqzequ", "yutahdply", "suvvqdiceuogcmv", "ainlwrwabqcwq", "fquzrlhdsnuwhhu", "tglnshmqlmkqqfbpf", "vaufbmwdrupcxpg", "zwwgloilddclufwze", "livgsrfvgtovcurzq", "wtjtdrlm", "edurtetzseifez", "ecqfdkebnamkfglk", "livgsrfvgtovcurzq", "wmpvjvzljhnaxvp", "ryubcgbzmxc", "pzlmeboecybxmetz", "hqpnoczciajvkbdy", "xpmxtfyvjrnujyxjh", "zwwgloilddclufwze", "khcyhttaaxp", "wlvmfxbleuot", "jzquemjzpvfbka", "vaufbmwdrupcxpg", "tglnshmqlmkqqfbpf", "mzvbgcizeeth", "cjjkmybleu", "orlzzpytpzazxr", "dhmiuqhqlsprxy", "mzfpofjn", "bfxbncez", "inuzvkgolupxelcal", "inhzsspqltvl", "wlvmfxbleuot", "livgsrfvgtovcurzq", "orlzzpytpzazxr", "yutahdply", "yutahdply", "orlzzpytpzazxr", "gdziaihbagl", "yltljjairlkrmdq", "mkmawbogphdttd", "aotjpvanljxe", "aeloeauxmc", "wmpvjvzljhnaxvp", "dhmiuqhqlsprxy", "yltljjairlkrmdq", "dnaaehrekqms", "khcyhttaaxp", "mzvbgcizeeth", "narvuaqmmkqhd", "rvihrzzkt", "bfufqsusp", "xrgfejybbkezgor", "vaufbmwdrupcxpg", "czlgbqzffodsoxng", "jrocadcojmybpxmuj", "yltljjairlkrmdq", "yltljjairlkrmdq", "bubwouozgs", "inhzsspqltvl", "bsybvehdny", "subzoyxjkfiwmfb", "livgsrfvgtovcurzq", "stkglpqdjzxmnlito", "evepphnzuw", "xrgfejybbkezgor", "rztcppnmud", "cjjkmybleu", "qyaxqaqxiwr", "ibwfxvxswjbecab", "xydwvemqvtgvzl", "hqpnoczciajvkbdy", "tglnshmqlmkqqfbpf", "dnaaehrekqms", "gkqrglav", "bfxbncez", "qvwvgzxqihvk", "umlzibkkpsyvpdol", "vaufbmwdrupcxpg", "khcyhttaaxp", "arigdtezmyz", "bubwouozgs", "fllqjtnxwmfoou", "xozoyaqxtbustrymo", "jrocadcojmybpxmuj", "rnlryins", "wtjtdrlm", "livgsrfvgtovcurzq", "gkqrglav", "orileazg", "uzlxmaoro", "ainlwrwabqcwq", "vaufbmwdrupcxpg", "vaufbmwdrupcxpg"};
        pairs = new String[][]{
                {"yutahdply", "yutahdply"},
                {"xozoyaqxtbustrymo", "xozoyaqxtbustrymo"},
                {"xozoyaqxtbustrymo", "xozoyaqxtbustrymo"},
                {"yutahdply", "yutahdply"},
                {"shfzcyboj", "orlzzpytpzazxr"},
                {"suvvqdiceuogcmv", "llrzqdnoxbscnkqy"},
                {"jkcmceinlyhi", "hqpnoczciajvkbdy"},
                {"hqpnoczciajvkbdy", "hqpnoczciajvkbdy"},
                {"rztcppnmud", "vdjccijgqk"},
                {"vdjccijgqk", "vdjccijgqk"},
                {"jkcmceinlyhi", "hqpnoczciajvkbdy"},
                {"rztcppnmud", "rztcppnmud"},
                {"vdjccijgqk", "vdjccijgqk"},
                {"hqpnoczciajvkbdy", "hqpnoczciajvkbdy"},
                {"umlzibkkpsyvpdol", "ryubcgbzmxc"},
                {"ryubcgbzmxc", "ryubcgbzmxc"},
                {"pzlmeboecybxmetz", "bsybvehdny"},
                {"rqbswlkw", "bsybvehdny"},
                {"bsybvehdny", "bsybvehdny"},
                {"umlzibkkpsyvpdol", "umlzibkkpsyvpdol"},
                {"ryubcgbzmxc", "ryubcgbzmxc"},
                {"rqbswlkw", "rqbswlkw"},
                {"pzlmeboecybxmetz", "pzlmeboecybxmetz"},
                {"bsybvehdny", "bsybvehdny"},
                {"dkhfozltuckwog", "zwwgloilddclufwze"},
                {"zfmpxgrevxp", "pyzcbpjhntpefbq"},
                {"gkqrglav", "czlgbqzffodsoxng"},
                {"tyxrlpmcy", "livgsrfvgtovcurzq"},
                {"shsgrqol", "cufxsgbpjgqvk"},
                {"rphnhtvnihyfkrgv", "yykdqtkkdacpbwtbq"},
                {"dhmiuqhqlsprxy", "ztisufueqzequ"},
                {"ibwfxvxswjbecab", "xydwvemqvtgvzl"},
                {"mkmawbogphdttd", "ainlwrwabqcwq"},
                {"pdxsxjop", "uzlxmaoro"},
                {"ooyllkxg", "khcyhttaaxp"},
                {"jrocadcojmybpxmuj", "jrocadcojmybpxmuj"},
                {"lkopigreodypvude", "lkopigreodypvude"},
                {"hqpnoczciajvkbdy", "rztcppnmud"},
                {"llrzqdnoxbscnkqy", "jrocadcojmybpxmuj"},
                {"cuewcvuy", "jzquemjzpvfbka"},
                {"wlvmfxbleuot", "bfufqsusp"},
                {"bfufqsusp", "bfufqsusp"},
                {"xpmxtfyvjrnujyxjh", "rpesfkhfjucj"},
                {"mzfpofjn", "rpesfkhfjucj"},
                {"rpesfkhfjucj", "rpesfkhfjucj"},
                {"xpmxtfyvjrnujyxjh", "mzfpofjn"},
                {"wlvmfxbleuot", "bfufqsusp"},
                {"rpesfkhfjucj", "xpmxtfyvjrnujyxjh"},
                {"cuewcvuy", "dnaaehrekqms"},
                {"dnaaehrekqms", "dnaaehrekqms"},
                {"rpesfkhfjucj", "wlvmfxbleuot"},
                {"lkopigreodypvude", "mzvbgcizeeth"},
                {"tglnshmqlmkqqfbpf", "bbchthovla"},
                {"orileazg", "filnwifbukdqijgr"},
                {"yltljjairlkrmdq", "xrgfejybbkezgor"},
                {"inuzvkgolupxelcal", "hgxrhkanzvzmsjpzl"},
                {"jzquemjzpvfbka", "iziepzqne"},
                {"muaskefecskjghzn", "iziepzqne"},
                {"hhrllhedyy", "wzflhbbgtc"},
                {"cemnayjhlnj", "hgtyntdmrgjh"},
                {"iziepzqne", "iziepzqne"},
                {"cuewcvuy", "dnaaehrekqms"},
                {"muaskefecskjghzn", "iziepzqne"},
                {"jzquemjzpvfbka", "muaskefecskjghzn"},
                {"dnaaehrekqms", "dnaaehrekqms"},
                {"jrocadcojmybpxmuj", "jrocadcojmybpxmuj"},
                {"llrzqdnoxbscnkqy", "suvvqdiceuogcmv"},
                {"suvvqdiceuogcmv", "suvvqdiceuogcmv"},
                {"bbchthovla", "bbchthovla"},
                {"rvihrzzkt", "tglnshmqlmkqqfbpf"},
                {"filnwifbukdqijgr", "pkirimjwvyxs"},
                {"tglnshmqlmkqqfbpf", "tglnshmqlmkqqfbpf"},
                {"rvihrzzkt", "tglnshmqlmkqqfbpf"},
                {"bbchthovla", "bbchthovla"},
                {"tglnshmqlmkqqfbpf", "tglnshmqlmkqqfbpf"},
                {"hjogoueazw", "lkopigreodypvude"},
                {"lkopigreodypvude", "lkopigreodypvude"},
                {"mzvbgcizeeth", "arigdtezmyz"},
                {"qvwvgzxqihvk", "arigdtezmyz"},
                {"arigdtezmyz", "arigdtezmyz"},
                {"mzvbgcizeeth", "arigdtezmyz"},
                {"qvwvgzxqihvk", "qvwvgzxqihvk"},
                {"hjogoueazw", "hjogoueazw"},
                {"subzoyxjkfiwmfb", "khcyhttaaxp"},
                {"subzoyxjkfiwmfb", "subzoyxjkfiwmfb"},
                {"khcyhttaaxp", "subzoyxjkfiwmfb"},
                {"ooyllkxg", "ooyllkxg"},
                {"orlzzpytpzazxr", "orlzzpytpzazxr"},
                {"oufzmjgplt", "oufzmjgplt"},
                {"shfzcyboj", "shfzcyboj"},
                {"oufzmjgplt", "oufzmjgplt"},
                {"orlzzpytpzazxr", "oufzmjgplt"},
                {"wrszraxxdum", "wrszraxxdum"},
                {"wrszraxxdum", "wrszraxxdum"},
                {"shfzcyboj", "wrszraxxdum"},
                {"yutahdply", "xozoyaqxtbustrymo"},
                {"umlzibkkpsyvpdol", "pzlmeboecybxmetz"},
                {"hgxrhkanzvzmsjpzl", "gwkkpxuvgp"},
                {"xrgfejybbkezgor", "wtjtdrlm"},
                {"wtjtdrlm", "wtjtdrlm"},
                {"yltljjairlkrmdq", "fllqjtnxwmfoou"},
                {"xrgfejybbkezgor", "wtjtdrlm"},
                {"filnwifbukdqijgr", "pkirimjwvyxs"},
                {"pkirimjwvyxs", "pkirimjwvyxs"},
                {"gdziaihbagl", "orileazg"},
                {"orileazg", "orileazg"},
                {"gdziaihbagl", "orileazg"},
                {"hlcsiukaroscfg", "orileazg"},
                {"hlcsiukaroscfg", "hlcsiukaroscfg"},
                {"gdziaihbagl", "gdziaihbagl"},
                {"ainlwrwabqcwq", "ainlwrwabqcwq"},
                {"uzlxmaoro", "bfxbncez"},
                {"qyaxqaqxiwr", "qyaxqaqxiwr"},
                {"pdxsxjop", "pdxsxjop"},
                {"pdxsxjop", "pdxsxjop"},
                {"subzoyxjkfiwmfb", "subzoyxjkfiwmfb"},
                {"uzlxmaoro", "bfxbncez"},
                {"bfxbncez", "bfxbncez"},
                {"qyaxqaqxiwr", "pdxsxjop"},
                {"ooyllkxg", "ooyllkxg"},
                {"hgxrhkanzvzmsjpzl", "ecqfdkebnamkfglk"},
                {"gwkkpxuvgp", "ecqfdkebnamkfglk"},
                {"ecqfdkebnamkfglk", "ecqfdkebnamkfglk"},
                {"yzxogkunvohdmro", "yzxogkunvohdmro"},
                {"inuzvkgolupxelcal", "yzxogkunvohdmro"},
                {"yzxogkunvohdmro", "yzxogkunvohdmro"},
                {"cjjkmybleu", "yzxogkunvohdmro"},
                {"inuzvkgolupxelcal", "inuzvkgolupxelcal"},
                {"ecqfdkebnamkfglk", "gwkkpxuvgp"},
                {"dwojnswr", "dkhfozltuckwog"},
                {"yltljjairlkrmdq", "fllqjtnxwmfoou"},
                {"fllqjtnxwmfoou", "fllqjtnxwmfoou"},
                {"wzflhbbgtc", "zzdvolqtndzfjvqqr"},
                {"dkhfozltuckwog", "dkhfozltuckwog"},
                {"zfmpxgrevxp", "stkglpqdjzxmnlito"},
                {"wzflhbbgtc", "wzflhbbgtc"},
                {"cjjkmybleu", "cjjkmybleu"},
                {"wgcjlntupylayse", "wgcjlntupylayse"},
                {"vyrvelteblnqaabc", "vyrvelteblnqaabc"},
                {"bvxiilsnsarhsyl", "zzdvolqtndzfjvqqr"},
                {"stkglpqdjzxmnlito", "stkglpqdjzxmnlito"},
                {"cemnayjhlnj", "cemnayjhlnj"},
                {"cemnayjhlnj", "cemnayjhlnj"},
                {"hgtyntdmrgjh", "hgtyntdmrgjh"},
                {"rnlryins", "vyrvelteblnqaabc"},
                {"hhrllhedyy", "vyrvelteblnqaabc"},
                {"rnlryins", "rnlryins"},
                {"fquzrlhdsnuwhhu", "zzdvolqtndzfjvqqr"},
                {"zzdvolqtndzfjvqqr", "bvxiilsnsarhsyl"},
                {"wmpvjvzljhnaxvp", "wmpvjvzljhnaxvp"},
                {"qnjidlmwmxxjgntez", "vyrvelteblnqaabc"},
                {"fquzrlhdsnuwhhu", "zzdvolqtndzfjvqqr"},
                {"zzdvolqtndzfjvqqr", "zzdvolqtndzfjvqqr"},
                {"edurtetzseifez", "rphnhtvnihyfkrgv"},
                {"wgcjlntupylayse", "wgcjlntupylayse"},
                {"zwwgloilddclufwze", "aeloeauxmc"},
                {"rphnhtvnihyfkrgv", "rphnhtvnihyfkrgv"},
                {"aeloeauxmc", "aeloeauxmc"},
                {"hgtyntdmrgjh", "wgcjlntupylayse"},
                {"rphnhtvnihyfkrgv", "rphnhtvnihyfkrgv"},
                {"cufxsgbpjgqvk", "cufxsgbpjgqvk"},
                {"mnrdscqkycodx", "shsgrqol"},
                {"qnjidlmwmxxjgntez", "hhrllhedyy"},
                {"shsgrqol", "shsgrqol"},
                {"vyrvelteblnqaabc", "qnjidlmwmxxjgntez"},
                {"zwwgloilddclufwze", "aeloeauxmc"},
                {"evepphnzuw", "rthpxoxyyiy"},
                {"rthpxoxyyiy", "rthpxoxyyiy"},
                {"aotjpvanljxe", "aotjpvanljxe"},
                {"aotjpvanljxe", "stkglpqdjzxmnlito"},
                {"dkhfozltuckwog", "dwojnswr"},
                {"rthpxoxyyiy", "pyzcbpjhntpefbq"},
                {"evepphnzuw", "evepphnzuw"},
                {"aeloeauxmc", "aeloeauxmc"},
                {"zfmpxgrevxp", "aotjpvanljxe"},
                {"stkglpqdjzxmnlito", "aotjpvanljxe"},
                {"bubwouozgs", "mkmawbogphdttd"},
                {"pyzcbpjhntpefbq", "rthpxoxyyiy"},
                {"gkqrglav", "gkqrglav"},
                {"czlgbqzffodsoxng", "czlgbqzffodsoxng"},
                {"yykdqtkkdacpbwtbq", "yykdqtkkdacpbwtbq"},
                {"dhmiuqhqlsprxy", "dhmiuqhqlsprxy"},
                {"ztisufueqzequ", "ztisufueqzequ"},
                {"ztisufueqzequ", "narvuaqmmkqhd"},
                {"narvuaqmmkqhd", "narvuaqmmkqhd"},
                {"narvuaqmmkqhd", "narvuaqmmkqhd"},
                {"ibwfxvxswjbecab", "ibwfxvxswjbecab"},
                {"dhmiuqhqlsprxy", "dhmiuqhqlsprxy"},
                {"xydwvemqvtgvzl", "wmpvjvzljhnaxvp"},
                {"wmpvjvzljhnaxvp", "wmpvjvzljhnaxvp"},
                {"xydwvemqvtgvzl", "wmpvjvzljhnaxvp"},
                {"ibwfxvxswjbecab", "ibwfxvxswjbecab"},
                {"bubwouozgs", "mkmawbogphdttd"},
                {"mkmawbogphdttd", "mkmawbogphdttd"},
                {"ainlwrwabqcwq", "ainlwrwabqcwq"},
                {"mkmawbogphdttd", "mkmawbogphdttd"},
                {"edurtetzseifez", "edurtetzseifez"},
                {"inhzsspqltvl", "inhzsspqltvl"},
                {"cufxsgbpjgqvk", "inhzsspqltvl"},
                {"yykdqtkkdacpbwtbq", "yykdqtkkdacpbwtbq"},
                {"mnrdscqkycodx", "mnrdscqkycodx"},
                {"shsgrqol", "shsgrqol"},
                {"cufxsgbpjgqvk", "inhzsspqltvl"},
                {"livgsrfvgtovcurzq", "livgsrfvgtovcurzq"},
                {"tyxrlpmcy", "tyxrlpmcy"},
                {"livgsrfvgtovcurzq", "livgsrfvgtovcurzq"},
                {"tyxrlpmcy", "tyxrlpmcy"},
                {"czlgbqzffodsoxng", "czlgbqzffodsoxng"},
                {"gkqrglav", "gkqrglav"},
        };
        assertEquals(true, solution1.areSentencesSimilarTwo(words1, words2, pairs));
    }

    @Test
    public void test5() {
        words1 = new String[]{"a", "very", "delicious", "meal"};
        words2 = new String[]{"one", "really", "good", "dinner"};
        pairs = new String[][]{
                {"great", "good"},
                {"extraordinary", "good"},
                {"well", "good"},
                {"wonderful", "good"},
                {"excellent", "good"},
                {"fine", "good"},
                {"nice", "good"},
                {"any", "one"},
                {"some", "one"},
                {"unique", "one"},
                {"the", "one"},
                {"an", "one"},
                {"single", "one"},
                {"a", "one"},
                {"truck", "car"},
                {"wagon", "car"},
                {"automobile", "car"},
                {"auto", "car"},
                {"vehicle", "car"},
                {"entertain", "have"},
                {"drink", "have"},
                {"eat", "have"},
                {"take", "have"},
                {"fruits", "meal"},
                {"brunch", "meal"},
                {"breakfast", "meal"},
                {"food", "meal"},
                {"dinner", "meal"},
                {"super", "meal"},
                {"lunch", "meal"},
                {"possess", "own"},
                {"keep", "own"},
                {"have", "own"},
                {"extremely", "very"},
                {"really", "very"},
                {"super", "very"},
        };
        assertEquals(false, solution1.areSentencesSimilarTwo(words1, words2, pairs));
    }

}